<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1536145363969' stop='1536145454359'>
    <name>Test gmail</name>
    <title>Test gmail</title>
    <test-cases>
        <test-case start='1536145363969' status='failed' stop='1536145454359'>
            <name>Validate user credentials</name>
            <title>Validate user credentials</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='80fb6dfe-96af-44e8-a79c-bb75229e1691-attachment.png' type='image/png' size='33037'/>
            </attachments>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (C:\Users\ddminh\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
                    at ontimeout (timers.js:498:11)
                    at tryOnTimeout (timers.js:323:5)
                    at Timer.listOnTimeout (timers.js:290:5)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>